name: 'Build and Push If Changed'
description: 'Build a Docker image and only push if content has changed'
inputs:
  context:
    description: 'Build context path'
    required: false
    default: '.'
  file:
    description: 'Path to Dockerfile'
    required: true
  tags:
    description: 'Image tags (space or newline separated)'
    required: true
  build-args:
    description: 'Build arguments (multiline string)'
    required: false
  platforms:
    description: 'Target platforms'
    required: false
    default: 'linux/amd64'

runs:
  using: 'composite'
  steps:
    - name: Build and conditionally push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=registry,ref=${{ inputs.tags }}
        cache-to: type=registry,ref=${{ inputs.tags }},mode=max
